--
-- PostgreSQL database dump
--

\restrict xGtKdpZ9TqtCH3GHu7cQOzaNU6IAagKA6FVupgEyMXOWJ0TSALnKgBtLGK2XdSp

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ActivityLogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ActivityLogs" (
    "Id" integer NOT NULL,
    "AssetId" integer NOT NULL,
    "Action" character varying(30) NOT NULL,
    "PerformedByUserId" integer NOT NULL,
    "TargetUserId" integer,
    "Details" character varying(2000),
    "Timestamp" timestamp with time zone NOT NULL
);


--
-- Name: ActivityLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ActivityLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ActivityLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Assets" (
    "Id" integer NOT NULL,
    "AssetTag" character varying(20) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Category" character varying(30) NOT NULL,
    "Brand" character varying(50),
    "Model" character varying(50),
    "SerialNumber" character varying(100),
    "PurchaseDate" date,
    "PurchaseCost" numeric(12,2),
    "Location" character varying(100),
    "Status" character varying(30) NOT NULL,
    "AssignedToUserId" integer,
    "AssignedAt" timestamp with time zone,
    "Notes" character varying(1000),
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


--
-- Name: Assets_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Assets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Assets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Tickets" (
    "Id" integer NOT NULL,
    "Title" character varying(150) NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "Priority" character varying(30) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "RelatedAssetId" integer,
    "ResolutionNote" character varying(2000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ResolvedAt" timestamp with time zone
);


--
-- Name: Tickets_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Tickets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tickets_Id_seq"
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "Department" character varying(100),
    "PasswordHash" text NOT NULL,
    "Role" character varying(30) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: ActivityLogs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ActivityLogs" ("Id", "AssetId", "Action", "PerformedByUserId", "TargetUserId", "Details", "Timestamp") FROM stdin;
1	1	Created	1	\N	Created AST-0003 (HP EliteBook 840)	2026-07-31 17:00:00+08
2	2	Created	1	\N	Created AST-0006 (Lenovo ThinkPad X1 Carbon)	2026-06-25 17:00:00+08
3	3	Created	1	\N	Created AST-0009 (HP Elite Tower 800)	2026-05-20 17:00:00+08
4	4	Created	1	\N	Created AST-0012 (LG 27UP850)	2026-04-14 17:00:00+08
5	4	Updated	1	\N	Status: In Service → Needs Repair	2026-04-24 17:00:00+08
6	5	Created	1	\N	Created AST-0015 (LG 24MP400)	2026-03-09 17:00:00+08
7	6	Created	1	\N	Created AST-0018 (Google Pixel 8)	2026-02-01 17:00:00+08
8	7	Created	1	\N	Created AST-0021 (HP LaserJet Pro M404)	2025-12-27 17:00:00+08
9	7	Updated	1	\N	Status: In Service → Needs Repair	2026-01-06 17:00:00+08
10	8	Created	1	\N	Created AST-0024 (Cisco Catalyst 1000 Switch)	2025-11-21 17:00:00+08
11	9	Created	1	\N	Created AST-0027 (Logitech MX Keys)	2025-10-16 17:00:00+08
12	10	Created	1	\N	Created AST-0028 (Logitech MX Master 3S)	2025-10-04 17:00:00+08
13	10	Updated	1	\N	Status: In Service → Retired	2025-10-14 17:00:00+08
14	11	Created	1	\N	Created AST-0030 (APC Back-UPS 1500)	2025-09-10 17:00:00+08
15	11	Updated	1	\N	Status: In Service → Retired	2025-09-20 17:00:00+08
16	12	Created	1	\N	Created AST-0001 (Dell Latitude 5440)	2026-08-24 17:00:00+08
17	12	Assigned	1	2	Assigned to Siti Aminah	2026-08-26 17:00:00+08
18	13	Created	1	\N	Created AST-0002 (Lenovo ThinkPad T14)	2026-08-12 17:00:00+08
19	13	Assigned	1	3	Assigned to Lim Wei Jie	2026-08-14 17:00:00+08
20	14	Created	1	\N	Created AST-0004 (MacBook Pro 14)	2026-07-19 17:00:00+08
21	14	Assigned	1	5	Assigned to Farid Ismail	2026-07-21 17:00:00+08
22	14	Updated	1	\N	Status: In Service → Needs Repair	2026-07-29 17:00:00+08
23	15	Created	1	\N	Created AST-0005 (Dell Latitude 7440)	2026-07-07 17:00:00+08
24	15	Assigned	1	6	Assigned to Tan Mei Ling	2026-07-09 17:00:00+08
25	16	Created	1	\N	Created AST-0007 (HP ProBook 450)	2026-06-13 17:00:00+08
26	16	Assigned	1	3	Assigned to Lim Wei Jie	2026-06-15 17:00:00+08
27	17	Created	1	\N	Created AST-0008 (Dell OptiPlex 7010)	2026-06-01 17:00:00+08
28	17	Assigned	1	4	Assigned to Priya Nair	2026-06-03 17:00:00+08
29	17	Updated	1	\N	Status: In Service → Under Maintenance	2026-06-11 17:00:00+08
30	18	Created	1	\N	Created AST-0010 (Lenovo ThinkCentre M70q)	2026-05-08 17:00:00+08
31	18	Assigned	1	6	Assigned to Tan Mei Ling	2026-05-10 17:00:00+08
32	19	Created	1	\N	Created AST-0011 (Dell UltraSharp 27)	2026-04-26 17:00:00+08
33	19	Assigned	1	2	Assigned to Siti Aminah	2026-04-28 17:00:00+08
34	20	Created	1	\N	Created AST-0013 (Samsung ViewFinity S6)	2026-04-02 17:00:00+08
35	20	Assigned	1	4	Assigned to Priya Nair	2026-04-04 17:00:00+08
36	21	Created	1	\N	Created AST-0014 (Dell P2422H)	2026-03-21 17:00:00+08
37	21	Assigned	1	5	Assigned to Farid Ismail	2026-03-23 17:00:00+08
38	22	Created	1	\N	Created AST-0016 (iPhone 15)	2026-02-25 17:00:00+08
39	22	Assigned	1	2	Assigned to Siti Aminah	2026-02-27 17:00:00+08
40	23	Created	1	\N	Created AST-0017 (Samsung Galaxy S24)	2026-02-13 17:00:00+08
41	23	Assigned	1	3	Assigned to Lim Wei Jie	2026-02-15 17:00:00+08
42	23	Updated	1	\N	Status: In Service → Under Maintenance	2026-02-23 17:00:00+08
43	24	Created	1	\N	Created AST-0019 (iPad Air)	2026-01-20 17:00:00+08
44	24	Assigned	1	5	Assigned to Farid Ismail	2026-01-22 17:00:00+08
45	25	Created	1	\N	Created AST-0020 (Samsung Galaxy Tab S9)	2026-01-08 17:00:00+08
46	25	Assigned	1	6	Assigned to Tan Mei Ling	2026-01-10 17:00:00+08
47	26	Created	1	\N	Created AST-0022 (Brother HL-L2375DW)	2025-12-15 17:00:00+08
48	26	Assigned	1	3	Assigned to Lim Wei Jie	2025-12-17 17:00:00+08
49	27	Created	1	\N	Created AST-0023 (Epson EcoTank L6270)	2025-12-03 17:00:00+08
50	27	Assigned	1	4	Assigned to Priya Nair	2025-12-05 17:00:00+08
51	28	Created	1	\N	Created AST-0025 (Ubiquiti UniFi AP)	2025-11-09 17:00:00+08
52	28	Assigned	1	6	Assigned to Tan Mei Ling	2025-11-11 17:00:00+08
53	29	Created	1	\N	Created AST-0026 (Fortinet FortiGate 40F)	2025-10-28 17:00:00+08
54	29	Assigned	1	2	Assigned to Siti Aminah	2025-10-30 17:00:00+08
55	30	Created	1	\N	Created AST-0029 (Jabra Evolve2 65)	2025-09-22 17:00:00+08
56	30	Assigned	1	5	Assigned to Farid Ismail	2025-09-24 17:00:00+08
\.


--
-- Data for Name: Assets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Assets" ("Id", "AssetTag", "Name", "Category", "Brand", "Model", "SerialNumber", "PurchaseDate", "PurchaseCost", "Location", "Status", "AssignedToUserId", "AssignedAt", "Notes", "IsDeleted", "CreatedAt", "UpdatedAt") FROM stdin;
1	AST-0003	HP EliteBook 840	Laptop	HP	EliteBook 840 G10	HP023757	2026-07-30	5599.00	Penang Office	InService	\N	\N	\N	f	2026-07-31 17:00:00+08	2026-07-31 17:00:00+08
2	AST-0006	Lenovo ThinkPad X1 Carbon	Laptop	Lenovo	X1 Carbon Gen 11	LE047514	2026-06-24	7499.00	HQ - Level 2	InService	\N	\N	\N	f	2026-06-25 17:00:00+08	2026-06-25 17:00:00+08
3	AST-0009	HP Elite Tower 800	Desktop	HP	Elite Tower 800 G9	HP071271	2026-05-19	4299.00	Server Room	InService	\N	\N	\N	f	2026-05-20 17:00:00+08	2026-05-20 17:00:00+08
4	AST-0012	LG 27UP850	Monitor	LG	27UP850-W	LG095028	2026-04-13	1899.00	HQ - Level 3	NeedsRepair	\N	\N	\N	f	2026-04-14 17:00:00+08	2026-04-14 17:00:00+08
5	AST-0015	LG 24MP400	Monitor	LG	24MP400-B	LG118785	2026-03-08	499.00	Store Room	InService	\N	\N	\N	f	2026-03-09 17:00:00+08	2026-03-09 17:00:00+08
6	AST-0018	Google Pixel 8	Phone	Google	Pixel 8	GO142542	2026-01-31	3199.00	Penang Office	InService	\N	\N	\N	f	2026-02-01 17:00:00+08	2026-02-01 17:00:00+08
7	AST-0021	HP LaserJet Pro M404	Printer	HP	LaserJet Pro M404dn	HP166299	2025-12-26	1599.00	HQ - Level 2	NeedsRepair	\N	\N	\N	f	2025-12-27 17:00:00+08	2025-12-27 17:00:00+08
8	AST-0024	Cisco Catalyst 1000 Switch	Network	Cisco	C1000-24T	CI190056	2025-11-20	3899.00	Server Room	InService	\N	\N	\N	f	2025-11-21 17:00:00+08	2025-11-21 17:00:00+08
9	AST-0027	Logitech MX Keys	Peripheral	Logitech	MX Keys	LO213813	2025-10-15	449.00	HQ - Level 3	InService	\N	\N	\N	f	2025-10-16 17:00:00+08	2025-10-16 17:00:00+08
10	AST-0028	Logitech MX Master 3S	Peripheral	Logitech	MX Master 3S	LO221732	2025-10-03	399.00	Penang Office	Retired	\N	\N	\N	f	2025-10-04 17:00:00+08	2025-10-04 17:00:00+08
11	AST-0030	APC Back-UPS 1500	Other	APC	BX1500MI	AP237570	2025-09-09	1299.00	Store Room	Retired	\N	\N	\N	f	2025-09-10 17:00:00+08	2025-09-10 17:00:00+08
12	AST-0001	Dell Latitude 5440	Laptop	Dell	Latitude 5440	DE007919	2026-08-23	4899.00	HQ - Level 2	InService	2	2026-08-26 17:00:00+08	\N	f	2026-08-24 17:00:00+08	2026-08-24 17:00:00+08
13	AST-0002	Lenovo ThinkPad T14	Laptop	Lenovo	ThinkPad T14 Gen 4	LE015838	2026-08-11	5299.00	HQ - Level 3	InService	3	2026-08-14 17:00:00+08	\N	f	2026-08-12 17:00:00+08	2026-08-12 17:00:00+08
14	AST-0004	MacBook Pro 14	Laptop	Apple	MacBook Pro 14 M3	AP031676	2026-07-18	8999.00	Server Room	NeedsRepair	5	2026-07-21 17:00:00+08	\N	f	2026-07-19 17:00:00+08	2026-07-19 17:00:00+08
15	AST-0005	Dell Latitude 7440	Laptop	Dell	Latitude 7440	DE039595	2026-07-06	6199.00	Store Room	InService	6	2026-07-09 17:00:00+08	\N	f	2026-07-07 17:00:00+08	2026-07-07 17:00:00+08
16	AST-0007	HP ProBook 450	Laptop	HP	ProBook 450 G10	HP055433	2026-06-12	3899.00	HQ - Level 3	InService	3	2026-06-15 17:00:00+08	\N	f	2026-06-13 17:00:00+08	2026-06-13 17:00:00+08
17	AST-0008	Dell OptiPlex 7010	Desktop	Dell	OptiPlex 7010	DE063352	2026-05-31	3599.00	Penang Office	UnderMaintenance	4	2026-06-03 17:00:00+08	\N	f	2026-06-01 17:00:00+08	2026-06-01 17:00:00+08
18	AST-0010	Lenovo ThinkCentre M70q	Desktop	Lenovo	ThinkCentre M70q	LE079190	2026-05-07	2999.00	Store Room	InService	6	2026-05-10 17:00:00+08	\N	f	2026-05-08 17:00:00+08	2026-05-08 17:00:00+08
19	AST-0011	Dell UltraSharp 27	Monitor	Dell	U2723QE	DE087109	2026-04-25	2399.00	HQ - Level 2	InService	2	2026-04-28 17:00:00+08	\N	f	2026-04-26 17:00:00+08	2026-04-26 17:00:00+08
20	AST-0013	Samsung ViewFinity S6	Monitor	Samsung	LS27A600	SA102947	2026-04-01	1299.00	Penang Office	InService	4	2026-04-04 17:00:00+08	\N	f	2026-04-02 17:00:00+08	2026-04-02 17:00:00+08
21	AST-0014	Dell P2422H	Monitor	Dell	P2422H	DE110866	2026-03-20	899.00	Server Room	InService	5	2026-03-23 17:00:00+08	\N	f	2026-03-21 17:00:00+08	2026-03-21 17:00:00+08
22	AST-0016	iPhone 15	Phone	Apple	iPhone 15 128GB	AP126704	2026-02-24	3999.00	HQ - Level 2	InService	2	2026-02-27 17:00:00+08	\N	f	2026-02-25 17:00:00+08	2026-02-25 17:00:00+08
23	AST-0017	Samsung Galaxy S24	Phone	Samsung	Galaxy S24	SA134623	2026-02-12	3699.00	HQ - Level 3	UnderMaintenance	3	2026-02-15 17:00:00+08	\N	f	2026-02-13 17:00:00+08	2026-02-13 17:00:00+08
24	AST-0019	iPad Air	Tablet	Apple	iPad Air M2	AP150461	2026-01-19	2999.00	Server Room	InService	5	2026-01-22 17:00:00+08	\N	f	2026-01-20 17:00:00+08	2026-01-20 17:00:00+08
25	AST-0020	Samsung Galaxy Tab S9	Tablet	Samsung	Galaxy Tab S9	SA158380	2026-01-07	3499.00	Store Room	InService	6	2026-01-10 17:00:00+08	\N	f	2026-01-08 17:00:00+08	2026-01-08 17:00:00+08
26	AST-0022	Brother HL-L2375DW	Printer	Brother	HL-L2375DW	BR174218	2025-12-14	899.00	HQ - Level 3	InService	3	2025-12-17 17:00:00+08	\N	f	2025-12-15 17:00:00+08	2025-12-15 17:00:00+08
27	AST-0023	Epson EcoTank L6270	Printer	Epson	EcoTank L6270	EP182137	2025-12-02	1199.00	Penang Office	InService	4	2025-12-05 17:00:00+08	\N	f	2025-12-03 17:00:00+08	2025-12-03 17:00:00+08
28	AST-0025	Ubiquiti UniFi AP	Network	Ubiquiti	U6-Pro	UB197975	2025-11-08	899.00	Store Room	InService	6	2025-11-11 17:00:00+08	\N	f	2025-11-09 17:00:00+08	2025-11-09 17:00:00+08
29	AST-0026	Fortinet FortiGate 40F	Network	Fortinet	FG-40F	FO205894	2025-10-27	2499.00	HQ - Level 2	InService	2	2025-10-30 17:00:00+08	\N	f	2025-10-28 17:00:00+08	2025-10-28 17:00:00+08
30	AST-0029	Jabra Evolve2 65	Peripheral	Jabra	Evolve2 65	JA229651	2025-09-21	999.00	Server Room	InService	5	2025-09-24 17:00:00+08	\N	f	2025-09-22 17:00:00+08	2025-09-22 17:00:00+08
\.


--
-- Data for Name: Tickets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Tickets" ("Id", "Title", "Description", "Priority", "Status", "CreatedByUserId", "RelatedAssetId", "ResolutionNote", "CreatedAt", "UpdatedAt", "ResolvedAt") FROM stdin;
1001	Level 3 printer keeps jamming	The HP LaserJet on Level 3 jams on almost every double-sided print job.	Medium	InProgress	4	7	\N	2026-09-16 18:00:00+08	2026-09-16 18:00:00+08	\N
1002	VPN disconnects every few minutes	When working from home the VPN drops every 5–10 minutes and I have to sign in again.	High	Open	2	\N	\N	2026-09-20 17:00:00+08	2026-09-20 17:00:00+08	\N
1003	Laptop setup for new hire	Please prepare a laptop for our new support agent starting next Monday.	Low	Closed	6	\N	Laptop AST-0005 prepared and handed over.	2026-09-02 19:00:00+08	2026-09-02 19:00:00+08	2026-09-05 00:00:00+08
1004	Request for a second monitor	A second screen would help with campaign reporting.	Low	Resolved	5	\N	Assigned AST-0014 (Dell P2422H).	2026-09-10 23:00:00+08	2026-09-10 23:00:00+08	2026-09-11 18:00:00+08
1005	Laptop battery drains within two hours	My laptop goes from full to empty in about two hours, even with only email and Excel open.	High	Open	2	12	\N	2026-09-21 16:30:00+08	2026-09-21 16:30:00+08	\N
1006	Phone screen cracked	Dropped my work phone; the screen is cracked and touch stops working near the top.	Medium	InProgress	3	23	\N	2026-09-18 22:00:00+08	2026-09-18 22:00:00+08	\N
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Users" ("Id", "Username", "FullName", "Email", "Department", "PasswordHash", "Role", "IsDeleted", "CreatedAt", "UpdatedAt") FROM stdin;
1	admin	Aiman Hakim	admin@company.local	IT Operations	$2a$11$b0tIfTooy.tzvknxo0EM7u09HPwWLQ0CqKQKPHtvpmLKK0pyaQ5Q2	Admin	f	2025-07-29 08:00:00+08	2025-07-29 08:00:00+08
2	user	Siti Aminah	user@company.local	Finance Operations	$2a$11$ahJYIMPQJMcD6LR3RF9i/OR/uLZuor2GzOGtqjrZXCOIUt.MCrBlm	User	f	2025-08-18 08:00:00+08	2025-08-18 08:00:00+08
3	weijie	Lim Wei Jie	weijie@company.local	Engineering	$2a$11$ahJYIMPQJMcD6LR3RF9i/OR/uLZuor2GzOGtqjrZXCOIUt.MCrBlm	User	f	2025-09-07 08:00:00+08	2025-09-07 08:00:00+08
4	priya	Priya Nair	priya@company.local	Human Resources	$2a$11$ahJYIMPQJMcD6LR3RF9i/OR/uLZuor2GzOGtqjrZXCOIUt.MCrBlm	User	f	2025-10-07 08:00:00+08	2025-10-07 08:00:00+08
5	farid	Farid Ismail	farid@company.local	Marketing	$2a$11$ahJYIMPQJMcD6LR3RF9i/OR/uLZuor2GzOGtqjrZXCOIUt.MCrBlm	User	f	2025-11-26 08:00:00+08	2025-11-26 08:00:00+08
6	meiling	Tan Mei Ling	meiling@company.local	Customer Support	$2a$11$ahJYIMPQJMcD6LR3RF9i/OR/uLZuor2GzOGtqjrZXCOIUt.MCrBlm	User	f	2026-03-06 08:00:00+08	2026-03-06 08:00:00+08
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260922085743_InitialCreate	10.0.12
\.


--
-- Name: ActivityLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ActivityLogs_Id_seq"', 56, true);


--
-- Name: Assets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Assets_Id_seq"', 30, true);


--
-- Name: Tickets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Tickets_Id_seq"', 1006, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 6, true);


--
-- Name: ActivityLogs PK_ActivityLogs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ActivityLogs"
    ADD CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id");


--
-- Name: Assets PK_Assets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Assets"
    ADD CONSTRAINT "PK_Assets" PRIMARY KEY ("Id");


--
-- Name: Tickets PK_Tickets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_ActivityLogs_AssetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ActivityLogs_AssetId" ON public."ActivityLogs" USING btree ("AssetId");


--
-- Name: IX_ActivityLogs_PerformedByUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ActivityLogs_PerformedByUserId" ON public."ActivityLogs" USING btree ("PerformedByUserId");


--
-- Name: IX_ActivityLogs_TargetUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ActivityLogs_TargetUserId" ON public."ActivityLogs" USING btree ("TargetUserId");


--
-- Name: IX_ActivityLogs_Timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ActivityLogs_Timestamp" ON public."ActivityLogs" USING btree ("Timestamp");


--
-- Name: IX_Assets_AssetTag; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Assets_AssetTag" ON public."Assets" USING btree ("AssetTag") WHERE ("IsDeleted" = false);


--
-- Name: IX_Assets_AssignedToUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Assets_AssignedToUserId" ON public."Assets" USING btree ("AssignedToUserId");


--
-- Name: IX_Assets_SerialNumber; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Assets_SerialNumber" ON public."Assets" USING btree ("SerialNumber") WHERE (("IsDeleted" = false) AND ("SerialNumber" IS NOT NULL));


--
-- Name: IX_Tickets_CreatedByUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tickets_CreatedByUserId" ON public."Tickets" USING btree ("CreatedByUserId");


--
-- Name: IX_Tickets_RelatedAssetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tickets_RelatedAssetId" ON public."Tickets" USING btree ("RelatedAssetId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email") WHERE ("IsDeleted" = false);


--
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username") WHERE ("IsDeleted" = false);


--
-- Name: ActivityLogs FK_ActivityLogs_Assets_AssetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ActivityLogs"
    ADD CONSTRAINT "FK_ActivityLogs_Assets_AssetId" FOREIGN KEY ("AssetId") REFERENCES public."Assets"("Id") ON DELETE RESTRICT;


--
-- Name: ActivityLogs FK_ActivityLogs_Users_PerformedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ActivityLogs"
    ADD CONSTRAINT "FK_ActivityLogs_Users_PerformedByUserId" FOREIGN KEY ("PerformedByUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: ActivityLogs FK_ActivityLogs_Users_TargetUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ActivityLogs"
    ADD CONSTRAINT "FK_ActivityLogs_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: Assets FK_Assets_Users_AssignedToUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Assets"
    ADD CONSTRAINT "FK_Assets_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: Tickets FK_Tickets_Assets_RelatedAssetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Assets_RelatedAssetId" FOREIGN KEY ("RelatedAssetId") REFERENCES public."Assets"("Id") ON DELETE RESTRICT;


--
-- Name: Tickets FK_Tickets_Users_CreatedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict xGtKdpZ9TqtCH3GHu7cQOzaNU6IAagKA6FVupgEyMXOWJ0TSALnKgBtLGK2XdSp

